"""
HMAC-based signing and verification for QR payment payloads.

The QR code contains a JSON payload signed with HMAC-SHA256.
This prevents tampering — a vendor can verify the payment was
generated by a legitimate device.
"""

import hmac
import hashlib
import json
from app.config import QR_SECRET_KEY


def sign_payload(data: dict) -> str:
    """
    Sign a dictionary payload with HMAC-SHA256.
    Returns a JSON string with the data + signature.
    
    The vendor app uses the same secret key to verify.
    In production, you'd use asymmetric keys (device signs, vendor verifies
    with public key). For the MVP, shared secret is fine.
    """
    # Serialize data deterministically
    payload_str = json.dumps(data, sort_keys=True, separators=(',', ':'))
    
    # Create HMAC signature
    signature = hmac.new(
        QR_SECRET_KEY.encode('utf-8'),
        payload_str.encode('utf-8'),
        hashlib.sha256
    ).hexdigest()
    
    # Return combined payload with signature
    signed = {
        "data": data,
        "signature": signature
    }
    return json.dumps(signed)


def verify_payload(signed_json: str) -> tuple[bool, dict]:
    """
    Verify a signed payload.
    Returns (is_valid, data_dict).
    """
    try:
        signed = json.loads(signed_json)
        data = signed["data"]
        received_sig = signed["signature"]
        
        # Recompute signature
        payload_str = json.dumps(data, sort_keys=True, separators=(',', ':'))
        expected_sig = hmac.new(
            QR_SECRET_KEY.encode('utf-8'),
            payload_str.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()
        
        is_valid = hmac.compare_digest(received_sig, expected_sig)
        return is_valid, data
    except (json.JSONDecodeError, KeyError):
        return False, {}